#!/bin/bash

python3 -c "import cv2; print('OpenCV 版本:', cv2.__version__)" 2>/dev/null
if [ $? -ne 0 ]; then
    echo "OpenCV 未安装，正在安装 opencv-python..."
    pip3 install opencv-python

    if python3 -c "import cv2; print('OpenCV 版本:', cv2.__version__)" 2>/dev/null; then
        echo "OpenCV 安装成功！"
    else
        echo "OpenCV 安装失败，请手动安装 sudo pip3 install opencv-python "
        exit 1
    fi
fi

cd NPU
make
make install
pip3 install -e ./
